"""The settings cell, which every notebook must have as its first cell. It is a
code cell with only comments, for instance:

  # NCrystal notebook settings
  # title: Introduction and basic usage of the NCrystal Python API
  # shortkey: intro
  # section: basics
  # requires: plot, widgets

Keys (title, shortkey and section are required):

  title           : Title of the notebook.
  shortkey        : Short unique key (lowercase letters and digits, at most 14
                    characters), used in URLs and on the command line.
  section         : Key of the section (see notebook_settings.toml).
  requires        : Requirements (see notebook_settings.toml). NCrystal itself
                    is always required.
  plugins         : NCrystal plugins (see notebook_settings.toml).
  import-ncrystal : "no" if the generated setup code should not import NCrystal
                    (default is "yes").
  max-line-length : Maximum length of lines in code cells, if different from
                    the default.
  timeout         : Timeout in seconds when running the notebook, if different
                    from the default.
  test-parameters : Values for tests (e.g. reduced statistics), as assignments
                    separated by semicolons (e.g. "n = 1000; m = 2"). The
                    notebook must then have a code cell tagged "parameters"
                    assigning these names, after which the test values are
                    assigned when testing (like papermill parameters).

When the tool generates code for the notebook (e.g. setup code for testing),
the code is added to the settings cell after a marker line (MARKER below), and
removed again when the notebook is brought back into its canonical form.
"""

import re

HEADER = '# NCrystal notebook settings'
MARKER = ('# ----- Generated by ncnotebookdevtool from the settings above.'
          ' Do not edit below. -----')

KEYS = ( 'title', 'shortkey', 'section', 'requires', 'plugins',
         'import-ncrystal', 'max-line-length', 'timeout', 'test-parameters' )
REQUIRED_KEYS = ( 'title', 'shortkey', 'section' )

_shortkey_re = re.compile(r'^[a-z0-9]{1,14}$')
_line_re = re.compile(r'^# ([a-z-]+): (.*)$')
_assign_re = re.compile(r'^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(\S.*?)\s*$')

class SettingsError(RuntimeError):
    pass

def split_settings_source( src ):
    """Split the source of a settings cell into the settings part and any
    generated part (after the marker)."""
    lines = src.splitlines()
    if MARKER in lines:
        i = lines.index(MARKER)
        return '\n'.join(lines[:i]), '\n'.join(lines[i+1:])
    return src, ''

def _parse_list( value ):
    return [ e for e in re.split(r'[,\s]+',value.strip()) if e ]

class NotebookSettings:

    def __init__( self, src ):
        """Parse the settings from the source of a settings cell (raises
        SettingsError if invalid)."""
        settings_src, _ = split_settings_source(src)
        lines = settings_src.rstrip('\n').split('\n')
        if not lines or lines[0].strip() != HEADER:
            raise SettingsError(f'first cell must start with "{HEADER}"')
        values = {}
        for line in lines[1:]:
            m = _line_re.match(line.rstrip())
            if not m:
                raise SettingsError(f'invalid line in settings cell: "{line}"'
                                    ' (expected "# key: value")')
            key, value = m.group(1), m.group(2).strip()
            if key not in KEYS:
                raise SettingsError(f'unknown key in settings cell: "{key}"')
            if key in values:
                raise SettingsError(f'duplicate key in settings cell: "{key}"')
            if not value:
                raise SettingsError(f'empty value for "{key}" in settings cell')
            values[key] = value
        for k in REQUIRED_KEYS:
            if k not in values:
                raise SettingsError(f'missing "{k}" in settings cell')
        self.title = values['title']
        self.shortkey = values['shortkey']
        if not _shortkey_re.match(self.shortkey):
            raise SettingsError(f'invalid shortkey "{self.shortkey}" (must be'
                                ' 1-14 lowercase letters or digits)')
        self.section = values['section']
        self.requires = _parse_list(values.get('requires',''))
        self.plugins = _parse_list(values.get('plugins',''))
        imp = values.get('import-ncrystal','yes')
        if imp not in ('yes','no'):
            raise SettingsError('import-ncrystal must be "yes" or "no"')
        self.import_ncrystal = ( imp == 'yes' )
        self.max_line_length = self._int( values, 'max-line-length' )
        self.timeout = self._int( values, 'timeout' )
        #Test parameters, as a list of (name,value) pairs:
        self.test_parameters = []
        for item in values.get('test-parameters','').split(';'):
            if not item.strip():
                continue
            m = _assign_re.match(item)
            if not m:
                raise SettingsError(f'invalid test parameter "{item.strip()}"'
                                    ' (expected "name = value")')
            self.test_parameters.append( ( m.group(1), m.group(2) ) )
        self.source = settings_src.rstrip('\n')

    @staticmethod
    def _int( values, key ):
        if key not in values:
            return None
        try:
            v = int(values[key])
        except ValueError:
            v = 0
        if v <= 0:
            raise SettingsError(f'{key} must be a positive integer')
        return v

class Notebook:
    """A notebook in the repository, with its settings (settings is None, and
    error is set, if the notebook or its settings are invalid)."""

    def __init__( self, path ):
        from .dirs import reporoot
        from .nbfile import load, source_str, NotebookFormatError
        self.path = path
        self.relpath = path.relative_to(reporoot()).as_posix()
        self.settings = None
        self.error = None
        try:
            self.nb = load(path)
        except NotebookFormatError as e:
            self.nb = None
            self.error = str(e)
            return
        cells = self.nb['cells']
        if not cells or cells[0]['cell_type'] != 'code':
            self.error = ('the first cell must be a code cell with the settings'
                          f' (starting with "{HEADER}")')
            return
        try:
            self.settings = NotebookSettings(source_str(cells[0]))
        except SettingsError as e:
            self.error = str(e)

    @property
    def shortkey( self ):
        return self.settings.shortkey if self.settings else None

    def parameters_cell_indices( self ):
        """Indices of code cells tagged "parameters"."""
        return [ i for i, c in enumerate(self.nb['cells'])
                 if c['cell_type'] == 'code'
                 and 'parameters' in c.get('metadata',{}).get('tags',[]) ]

def find_notebooks():
    """All notebooks in the repository, sorted by path."""
    from .dirs import notebooks_dir
    paths = sorted( p for p in notebooks_dir().rglob('*.ipynb')
                    if '.ipynb_checkpoints' not in p.parts )
    return [ Notebook(p) for p in paths ]

def select_notebooks( args, notebooks = None ):
    """The notebooks given by shortkeys or paths (all notebooks if args is
    empty). Raises SystemExit for unknown notebooks."""
    import pathlib
    notebooks = notebooks if notebooks is not None else find_notebooks()
    if not args:
        return notebooks
    res = []
    for a in args:
        p = pathlib.Path(a)
        if p.suffix == '.ipynb':
            p = p.absolute().resolve()
            hits = [ nb for nb in notebooks if nb.path.resolve() == p ]
        else:
            hits = [ nb for nb in notebooks if nb.shortkey == a ]
        if not hits:
            raise SystemExit(f'ERROR: Unknown notebook: {a} (give a path to'
                             ' a notebook in the repository or a shortkey)')
        for nb in hits:
            if nb not in res:
                res.append(nb)
    return res
