"""The settings cell, which every notebook must have as its first cell. It is a
code cell with only comments, for instance:

  # NCrystal notebook settings
  # title: Introduction and basic usage of the NCrystal Python API
  # menutitle: Python API basics
  # shortkey: intro
  # section: start
  # sort-value: 100
  # requires: plot, widgets

Keys (title, menutitle, shortkey, section and sort-value are required):

  title           : Title of the notebook.
  menutitle       : Short title (at most 30 characters), for the menu of the
                    website.
  shortkey        : Short unique key (lowercase letters and digits, at most 14
                    characters), used in URLs and on the command line.
  section         : Key of the section (see notebook_settings.toml).
  sort-value      : Integer giving the order of the notebooks in a section:
                    larger values come later. Notebooks in the same section
                    must have different values.
  requires        : Requirements (see notebook_settings.toml). NCrystal itself
                    is always required.
  plugins         : NCrystal plugins (see notebook_settings.toml).
  slow            : "yes" for notebooks known to take long to run (they can
                    then be skipped with --skip-slow, e.g. while debugging).
  import-ncrystal : "no" if the generated setup code should not import NCrystal
                    (default is "yes").
  max-line-length : Maximum length of lines in code cells, if different from
                    the default.
  test-parameters : Values for tests (e.g. reduced statistics), as assignments
                    separated by semicolons (e.g. "n = 1000; m = 2"). Each
                    name must be assigned (at the start of a line) in exactly
                    one code cell of the notebook, after which its test value
                    is assigned when testing (see assignment_cells).

When the tool generates setup code for testing a notebook, the code is added
to the settings cell after a marker line (MARKER below). For editing, it is in
a separate cell after the settings cell instead (see expand.py). Either is
removed again when the notebook is brought back into its canonical form.
"""

import re

HEADER = '# NCrystal notebook settings'
MARKER = ('# ----- Generated by ncnotebookdevtool from the settings above.'
          ' Do not edit below. -----')

KEYS = ( 'title', 'menutitle', 'shortkey', 'section', 'sort-value',
         'requires', 'plugins', 'import-ncrystal', 'max-line-length',
         'test-parameters', 'slow' )
REQUIRED_KEYS = ( 'title', 'menutitle', 'shortkey', 'section',
                  'sort-value' )
MAX_MENUTITLE_LENGTH = 30

_shortkey_re = re.compile(r'^[a-z0-9]{1,14}$')
_line_re = re.compile(r'^# ([a-z-]+): (.*)$')
_assign_re = re.compile(r'^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(\S.*?)\s*$')

class SettingsError(RuntimeError):
    pass

def split_settings_source( src ):
    """Split the source of a settings cell into the settings part and any
    generated part (after the marker)."""
    lines = src.splitlines()
    if MARKER in lines:
        i = lines.index(MARKER)
        return '\n'.join(lines[:i]), '\n'.join(lines[i+1:])
    return src, ''

def _parse_list( value ):
    return [ e for e in re.split(r'[,\s]+',value.strip()) if e ]

class NotebookSettings:

    def __init__( self, src ):
        """Parse the settings from the source of a settings cell (raises
        SettingsError if invalid)."""
        settings_src, _ = split_settings_source(src)
        lines = settings_src.rstrip('\n').split('\n')
        if not lines or lines[0].strip() != HEADER:
            raise SettingsError(f'first cell must start with "{HEADER}"')
        values = {}
        for line in lines[1:]:
            m = _line_re.match(line.rstrip())
            if not m:
                raise SettingsError(f'invalid line in settings cell: "{line}"'
                                    ' (expected "# key: value")')
            key, value = m.group(1), m.group(2).strip()
            if key not in KEYS:
                raise SettingsError(f'unknown key in settings cell: "{key}"')
            if key in values:
                raise SettingsError(f'duplicate key in settings cell: "{key}"')
            if not value:
                raise SettingsError(f'empty value for "{key}" in settings cell')
            values[key] = value
        for k in REQUIRED_KEYS:
            if k not in values:
                raise SettingsError(f'missing "{k}" in settings cell')
        self.title = values['title']
        self.menutitle = values['menutitle']
        if len(self.menutitle) > MAX_MENUTITLE_LENGTH:
            raise SettingsError(f'menutitle "{self.menutitle}" is longer than'
                                f' {MAX_MENUTITLE_LENGTH} characters')
        self.shortkey = values['shortkey']
        if not _shortkey_re.match(self.shortkey):
            raise SettingsError(f'invalid shortkey "{self.shortkey}" (must be'
                                ' 1-14 lowercase letters or digits)')
        self.section = values['section']
        try:
            self.sort_value = int(values['sort-value'])
        except ValueError:
            raise SettingsError('sort-value must be an integer') from None
        self.requires = _parse_list(values.get('requires',''))
        self.plugins = _parse_list(values.get('plugins',''))
        imp = values.get('import-ncrystal','yes')
        if imp not in ('yes','no'):
            raise SettingsError('import-ncrystal must be "yes" or "no"')
        self.import_ncrystal = ( imp == 'yes' )
        slow = values.get('slow','no')
        if slow not in ('yes','no'):
            raise SettingsError('slow must be "yes" or "no"')
        self.slow = ( slow == 'yes' )
        self.max_line_length = self._int( values, 'max-line-length' )
        #Test parameters, as a list of (name,value) pairs:
        self.test_parameters = []
        for item in values.get('test-parameters','').split(';'):
            if not item.strip():
                continue
            m = _assign_re.match(item)
            if not m:
                raise SettingsError(f'invalid test parameter "{item.strip()}"'
                                    ' (expected "name = value")')
            self.test_parameters.append( ( m.group(1), m.group(2) ) )
        self.source = settings_src.rstrip('\n')

    @staticmethod
    def _int( values, key ):
        if key not in values:
            return None
        try:
            v = int(values[key])
        except ValueError:
            v = 0
        if v <= 0:
            raise SettingsError(f'{key} must be a positive integer')
        return v

class Notebook:
    """A notebook in the repository, with its settings (settings is None, and
    error is set, if the notebook or its settings are invalid)."""

    def __init__( self, path ):
        from .dirs import reporoot
        from .nbfile import NotebookFormatError, load, source_str
        self.path = path
        self.relpath = path.relative_to(reporoot()).as_posix()
        self.settings = None
        self.error = None
        try:
            self.nb = load(path)
        except NotebookFormatError as e:
            self.nb = None
            self.error = str(e)
            return
        cells = self.nb['cells']
        if not cells or cells[0]['cell_type'] != 'code':
            self.error = ('the first cell must be a code cell with the settings'
                          f' (starting with "{HEADER}")')
            return
        try:
            self.settings = NotebookSettings(source_str(cells[0]))
        except SettingsError as e:
            self.error = str(e)

    @property
    def shortkey( self ):
        return self.settings.shortkey if self.settings else None

def assignment_cells( cells, name ):
    """Indices of the code cells assigning the name at the start of a line
    (e.g. "n = 1000000"), where the test value of a test parameter with this
    name is assigned when testing (in a cell inserted after it)."""
    from .nbfile import source_str
    pattern = re.compile( '^' + re.escape(name) + r'\s*=(?!=)', re.M )
    return [ i for i, c in enumerate(cells)
             if c['cell_type'] == 'code' and pattern.search(source_str(c)) ]

def find_notebooks():
    """All notebooks in the repository, sorted by path."""
    from .dirs import notebooks_dir
    paths = sorted( p for p in notebooks_dir().rglob('*.ipynb')
                    if '.ipynb_checkpoints' not in p.parts )
    return [ Notebook(p) for p in paths ]

def select_notebooks( args, notebooks = None ):
    """The notebooks given by shortkeys or paths (all notebooks if args is
    empty). Raises SystemExit for unknown notebooks."""
    import pathlib
    notebooks = notebooks if notebooks is not None else find_notebooks()
    if not args:
        return notebooks
    res = []
    for a in args:
        p = pathlib.Path(a)
        if p.suffix == '.ipynb':
            p = p.absolute().resolve()
            hits = [ nb for nb in notebooks if nb.path.resolve() == p ]
        else:
            hits = [ nb for nb in notebooks if nb.shortkey == a ]
        if not hits:
            raise SystemExit(f'ERROR: Unknown notebook: {a} (give a path to'
                             ' a notebook in the repository or a shortkey)')
        for nb in hits:
            if nb not in res:
                res.append(nb)
    return res

def section_notebooks( notebooks, section_key ):
    """The notebooks of a section (with valid settings), in their order (by
    sort-value)."""
    nbs = [ nb for nb in notebooks
            if nb.settings and nb.settings.section == section_key ]
    return sorted( nbs, key = lambda nb : nb.settings.sort_value )
